--- 
components: 
  schemas:
    IoTdevice:
      required:
        - deviceName 
        - publishFrequency
        - messageSize
      description: 'Iot devices data model is intended to represent iot devices'
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
           description: 'NGSI Entity type. It has to be Device'
           enum:
             - Device
           type: string
           x-ngsi:
            type: Property
        deviceName: 
          description: 'Name of the device'
          type: string
          minLength: 1
          maxLength: 256
          x-ngsi:
            type: Property          
        publishFrequency:
          description: 'Publish frequency of the device'
          type: number
          minimum: 1
          maximum: 100
          x-ngsi:
            type: Property         
        messageSize:
          description: 'Message size of the device'
          type: number
          minimum: 1
          maximum: 100
          x-ngsi:
            type: Property
        distribution:
          description: 'Distribution of the device'
          type: string
          x-ngsi:
            type: Property
        publishesTo:
          description: 'Topics to which the device publishes'
          type: array
          items:
            type: string
          x-ngsi:
            type: Property
        controlledObservation:
          description: "The observation types connected with the device."
          type: array
          x-ngsi:
            type: Property
        observations:
          description: "List of id's of the observations connected with the device."
          type: array
          x-ngsi:
            type: Relationship
        controlledActuationCommands:
          description: "The actuation types connected with the device."
          type: array
          x-ngsi:
            type: Property
        actuationCommands:
          description: "List of id's of the actuations connected with the device."
          type: array
          x-ngsi:
            type: Relationship
        inSpace:
          description: "In which smart space the device is deployed in"
          type: string
          x-ngsi:
            type: Relationship
    Observation:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be Observation'
          enum:
            - Observation
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the observation."
          type: string
          x-ngsi:
            type: Property
        category:
          description: "The category of the observation."
          type: string
          x-ngsi:
            type: Property         
        dateModified:
          description: "The date that the observation was modified."
          type: string
          x-ngsi:
            type: Property
        measurement:
            required:
              - value
              - measurementUnit
            type: object
            properties:
              value: number
              type: string
              measurementUnit: string
              description: "The value of the observation."
            x-ngsi:
              type: Property
        measurementType:
          description: "The type of the measurement of the observation."
          type: string
          x-ngsi:
            type: Property
    Space:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be Space'
          enum:
            - Space
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the space."
          type: string
          x-ngsi:
            type: Property
    VirtualSensor:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be VirtualSensor'
          enum:
            - VirtualSensor
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the virtual sensor."
          type: string
          x-ngsi:
            type: Property
        category:
          description: "The category of the virtual sensor."
          type: string
          x-ngsi:
            type: Property         
        measurement:
            required:
              - value
              - measurementUnit
            type: object
            properties:
              value: number
              type: string
              measurementUnit: string
              description: "The value of the virtual sensor."
            x-ngsi:
              type: Property
        measurementType:
          description: "The type of the measurement of the virtual sensor."
          type: string
          x-ngsi:
            type: Property
        observations:
          description: "List of id's of the observations of the virtual sensor."
          type: array
          x-ngsi:
            type: Relationship
    ActuationCommand:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be ActuationCommand'
          enum:
            - ActuationCommand
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the actuation."
          type: string
          x-ngsi:
            type: Property
    Application:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be Application'
          enum:
            - Application
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the application."
          type: string
          x-ngsi:
            type: Property
        applicationCategory:
          description: "The category of which the application belongs to."
          type: string
          x-ngsi:
            type: Relationship
        observation:
          description: "The observation that the application is using."
          type: string
          x-ngsi:
            type: Relationship 
    ApplicationCategory:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be ApplicationCategory'
          enum:
            - ApplicationCategory
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the application category."
          type: string
          x-ngsi:
            type: Property
        qosRequirement:
          description: "The QOS requirements of the application category."
          type: string
          x-ngsi:
            type: Relationship        
    QOSRequirement:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be QOSRequirement'
          enum:
            - QOSRequirement
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the QOS requirement."
          type: string
          x-ngsi:
            type: Property
    SmartEnvironment:
      required:
        - id
        - type
      properties:
        id:
          anyOf: &anyof
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
          format: uri
          type: string
          description: "Unique identifier of the entity"
          x-ngsi:
            type: Property
        type:
          description: 'NGSI Entity type. It has to be SmartEnvironment'
          enum:
            - SmartEnvironment
          type: string
          x-ngsi:
            type: Property
        name:
          description: "The name of the smart environment."
          type: string
          x-ngsi:
            type: Property
        deployedApplication:
          description: "The application deployed in the smart environment."
          type: string
          x-ngsi:
            type: Relationship


info: 
  description: "Data model intended to represent smart space entities"
  title: "Smart Space Data Model"
  version: "1.0.0"
openapi: "3.0.0"
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object