--- 
components: 
  schemas:
    Device:
      allOf:
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/device.yaml#/Device"
      properties:         
        publishFrequency:
          description: 'Publish frequency of the device'
          type: number
          x-ngsi:
            type: Property
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"        
        messageSize:
          description: 'Message size of the device'
          type: number
          x-ngsi:
            type: Property
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
        dataDistribution:
          description: 'Data distribution of the device'
          type: string
          x-ngsi:
            type: Property
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
        capturesObservations:
          description: "The observations captured by the device."
          type: array
          x-ngsi:
            type: Property
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
        generatesActuationCommand:
          description: "Actuation command generated by the device."
          type: string
          x-ngsi:
            type: Relationship
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
        receivesActuationCommand:
          description: "Actuation command received by the device."
          type: string
          x-ngsi:
            type: Relationship
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
        isDeployedIn:
          description: "In which smart space the device is deployed in"
          type: string
          x-ngsi:
            type: Relationship
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
    Observation:
      properties:
        name:
          description: "The name of the observation."
          type: string
          x-ngsi:
            type: Property
        isCapturedBy:
          description: "The device that captures the observation."
          type: array
          x-ngsi:
            type: Relationship
        isReceivedBy:
          description: "The virtual sensor that receives the observation."
          type: array
          x-ngsi:
            type: Relationship
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"         
    Space:
      properties:
        name:
          description: "The name of the space."
          type: string
          x-ngsi:
            type: Property
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
    VirtualSensor:
      properties:
        name:
          description: "The name of the virtual sensor."
          type: string
          x-ngsi:
            type: Property
        processingRate:
          description: "The processing rate of the application."
          type: number
          x-ngsi:
            type: Property
        processingDistribution:
          description: "The processing distribution of the application."
          type: string
          x-ngsi:
            type: Property
        publishFrequency:
          description: 'Publish frequency of the device'
          type: number
          x-ngsi:
            type: Property         
        messageSize:
          description: 'Message size of the device'
          type: number
          x-ngsi:
            type: Property
        generatesObservation:
          description: "The observations generated by the virtual sensor."
          type: array
          x-ngsi:
            type: Relationship
        receivesObservation:
          description: "The observations received by the virtual sensor."
          type: array
          x-ngsi:
            type: Relationship
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
    ActuationCommand:
      properties:
         name:
          description: "The name of the actuation."
          type: string
          x-ngsi:
            type: Property
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
    Application:
      properties:
        name:
          description: "The name of the application."
          type: string
          x-ngsi:
            type: Property
        priority:
          description: "The priority of the application."
          type: number
          x-ngsi:
            type: Property
        processingRate:
          description: "The processing rate of the application."
          type: number
          x-ngsi:
            type: Property
        processingDistribution:
          description: "The processing distribution of the application."
          type: string
          x-ngsi:
            type: Property
        belongsToCategory:
          description: "The category of which the application belongs to."
          type: string
          x-ngsi:
            type: Relationship
        receivesObservation:
          description: "The observations received by the application."
          type: array
          x-ngsi:
            type: Relationship
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
    ApplicationCategory:
      properties:
        name:
          description: "The name of the application category."
          type: string
          x-ngsi:
            type: Property
        hasQoSRequirement:
          description: "The QOS requirements of the application category."
          type: string
          x-ngsi:
            type: Relationship
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"   
    QoSRequirement:
      properties:
        name:
          description: "The name of the QOS requirement."
          type: string
          x-ngsi:
            type: Property
        maxResponseTime:
          description: "The maximum response time of the QOS requirement."
          type: number
          x-ngsi:
            type: Property
        minThroughput: 
          description: "The minimum throughput of the QOS requirement."
          type: number
          x-ngsi:
            type: Property
        maxDropRate: 
          description: "The maximum drop rate of the QOS requirement."
          type: number
          x-ngsi:
            type: Property     
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
    SmartEnvironment:
      allOf: 
        - $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Building"
      properties:
        name:
          description: "The name of the smart environment."
          type: string
          x-ngsi:
            type: Property
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
        hasDeployedApplication:
          description: "The application deployed in the smart environment."
          type: string
          x-ngsi:
            type: Relationship
            uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/SAMSGBLab/edict--datamodels/main/context.json#"

info: 
  description: "Data model intended to represent smart space entities"
  title: "Smart Space Data Model"
  version: "1.0.0"
openapi: "3.0.0"
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object